# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_xfaostat_L200_ExportCSV
#'
#' Generate supply utilization balance in primary equivalent
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs, a vector of output names, or (if
#'   \code{command} is "MAKE") all the generated outputs
#' @details This chunk compiles balanced supply utilization data in primary equivalent in GCAM region and commodities.
#' @importFrom assertthat assert_that
#' @importFrom dplyr summarize bind_rows filter if_else inner_join left_join mutate rename select n group_by_at
#' first case_when vars
#' @importFrom tibble tibble
#' @importFrom tidyr complete drop_na gather nesting spread replace_na
#' @author XZ 2022
module_xfaostat_L200_ExportCSV <- function(command, ...) {

  MODULE_INPUTS <-
    c("Bal_new_all",
      "FBSH_CB",
      "SUA_food_macronutrient_rate")

  MODULE_OUTPUTS <-
    c("GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019",
      "GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean",
      "GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009")

  if(command == driver.DECLARE_INPUTS) {
    return(MODULE_INPUTS)
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(MODULE_OUTPUTS)
  } else if(command == driver.MAKE) {

    year <- value <- Year <- Value <- FAO_country <- iso <- NULL    # silence package check.

    all_data <- list(...)[[1]]

    # Load required inputs ----

    get_data_list(all_data, MODULE_INPUTS, strip_attributes = TRUE)


    ## *GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019 ----

    Bal_new_all %>% filter(value != 0.0) %>%
      transmute(area_code, item_code, element, year, value) ->
      GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019

    output_csv_data("GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019",
                    col_type_nonyear = "iifin",
                    title = "Supply_utilization_accounting for all FAO items in 2010 to 2019",
                    unit = "1000 tonnes", code = "SCL",
                    description = "Data is compiled and generated by gcamdata-FAOSTAT. Data is balanced in trade, supply_utilization, and storage",
                    out_dir = DIR_OUT_CSV, GZIP = T)


    # ## *GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020 ----
    #
    # FF_load_RDS("TM_bilateral", DATA_FOLDER_PROC = DIR_PROCESSED_RDS)
    #
    #
    # TM_bilateral %>% filter(year >= min(Hist_Year_FBS)) %>%
    #   FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(SUDAN2012_MERGE = T) %>%
    #   # merge Sudan and South Sudan
    #   FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(.FAO_AREA_CODE_COL = "source_code",
    #                                              .AREA_COL = "source",
    #                                              SUDAN2012_MERGE = T) ->
    #   TM_bilateral1
    # TM_bilateral1 %>% filter(value != 0.0) %>%
    #   transmute(area_code, item_code, source_code, year, value) ->
    #   GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020
    #
    #
    # output_csv_data("GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020",
    #                 col_type_nonyear = "iiiin",
    #                 title = "BiTrade for all available FAO items in 2010 to 2019",
    #                 unit = "1000 tonnes", code = "TM",
    #                 description = "Data is compiled and generated by gcamdata-FAOSTAT. Bilateral trade data.",
    #                 out_dir = DIR_OUT_CSV, GZIP = T)
    #



    ## *GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009 ----

    FBSH_CB%>%
      # merge Sudan and South Sudan
      FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(SUDAN2012_MERGE = T) ->
      FBSH_CB


    FBSH_CB %>% mutate(unit = "1000 tonnes", value = value / 1000) %>%
      filter(year <= 2009)  %>%
      filter(!is.na(year)) %>%
      spread(year, value) ->
      GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009


    output_csv_data("GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009",
                    col_type_nonyear = "iiccc",
                    title = "Old FAO food balance sheet in primary equilvalent in 1973 to 2009",
                    unit = "1000 tonnes", code = "FBSH",
                    description = "Data is compiled and generated by gcamdata-FAOSTAT. FBSH and CB include old food and nonfood balances.",
                    out_dir = DIR_OUT_CSV, GZIP = T)
    # ******************************----

    # Macronutrient ----

    ## *GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean----


    SUA_food_macronutrient_rate ->
      GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean


    # Fix Sudan with code 206 and 276 after 2012
    if (206 %in% GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean$area_code == F) {
      GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean %>%
        filter(area_code  == 276) %>% mutate(area_code  = 206) %>%
        bind_rows(GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean) ->
        GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean
    }


    output_csv_data("GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean",
                    col_type_nonyear = "iicnnn",
                    title = "Macronutrient conversion factor for food items, mean values of 2010 to 2019",
                    unit = "calories per g or (fat or protein) percentage", code = "SCL",
                    description = "Data is compiled and generated by gcamdata-FAOSTAT. Macronutrient conversion factor for all available FAO food items.",
                    out_dir = DIR_OUT_CSV, GZIP = T)




    return_data(MODULE_OUTPUTS)


  } else {
    stop("Unknown command")
  }
}
