---
title: "News"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{News}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
# 2024 updates


2024-10-17
* Merge the BYU and PCE branches into master.

## Structure change to make the package accessible to all modelers (not just GCAM)  
* GCAM specific chunks are added in `DISABLED_MODULES` in `constants.R`.  
* `write_csv_model` is added to `driver_drake()`. If `write_csv_model = GCAM`, related CSV will be exported to `output/gcamfaostat_GCAM`.   
* Prepare for the next release  

## **Raw data archive 2024**
* Input data updated to include 2022. Both remote archive and prebuilt data have been updated.  
* The source data downloaded from FAOSTAT is archived at a [Zenodo repository](https://zenodo.org/deposit/13941470).


2024-4-22
# **JOSS Published**
* gcamfaostat v1.0.0
* doi.org/10.21105/joss.06388

2024-2-11

* Update trade related figures in [Cast Study](https://jgcri.github.io/gcamfaostat/articles/vignette_use_cases.html#faostat-raw-data-and-processing-output-updates)

2024-1-28

* The first version of gcamfaostat is still being processed/reviewed at JOSS
* We now create a release version to have a snapshot of this version (replicating the processing for GCAM v7.0 AgLU in data)
* Next stages of development:
  (1) BYU: GCAM base year update to 2021 and 
  (2) PCE: primary commodity equivalent processing and method documentation
* Possibly adding IFPRI SPAM data in the processing chain  

# 2023 updates

# **JOSS submission**
2023-11-10

* gcamfaostat is now submitted to JOSS for review and publication
* gcamfaostat v1.0.0 includes the data generated for the Global Change Analysis Model v7.0 [GCAM v7.0](https://github.com/JGCRI/gcam-core/releases/tag/gcam-v7.0). 
* We will make an official release after the JOSS review.

2023-11-09
# FAOSTAT (in the recent Oct release) provide 2021 data
# We will now update gcamfaostat to include the latest data and for GCAM BYU
# A new **BYU branch** is created for this task


2023-11-08

* All Github Action test passed. Badges added!

2023-11-07

* All documentations down, including paper.md
* Coauthor comments resolved.
* Creating a release version and submitting to JOSS. 

# October 2023 updates
2023-10-30  
* Vignettes completed

2023-10-25   
ToDo before JOSS submission  

* Check package license (PNNL)
* Check Zenodo license for FAOSTAT data [*Done*: `CC BY-NC-SA`]
* Test & Check; Adding GitHub tests/badges 

2023-10-24   

* Visualization Page is live now
* `gcamfaostat` moved to the JGCRI GitHub account

## FAOSTAT Commodity Balance (CB) updates
2023-09-25 
* Good news: It seems FAOSTAT just made the updated Commodity Balance (CB) dataset available. Previously, it only includes data up to 2013, i.e., consistent with FBSH. It is now adding a new dataset that include data from 2010-2020, consistent with FBH.
* However: 
  + The `update history` on FAOSTAT might not be the history of data availability. It says last update was 2022-12-23. But per 2023-08-20 archive, the data was still not available.
  + Bulk download seems not enabled yet.
  + Dataset code will likely change. CB seems reserved for the new data and the old one might be CBH. 
* Stay tuned.

## Goals for the next version include:
2023-09-25  

* Improve the documentation and the visualization of the *module_aglu_L100.FAO_SUA_PrimaryEquivalent* module
  + The module developed a new method of primary commodity equivalent aggregation to aggregate supply-utilization-accounting (SUA) data for items along the supply chain (e.g., wheat flour, bran, and germ to wheat-primary-equivalent). 
  + The method preserves balance across space (trade balance), time (storage carryover), supply-utilization, and the combination of these dimensions with minimal adjustments. 
  + We have applies the new method of primary equivalent aggregation to aggregating FAO ~500 SUA (SCL) items to ~100 primary equivalent items in FAO Food Balance Sheet (FBS).
* Compare the results from the new primary commodity equivalent method with the FBS data compiled using FAOSTAT method (never disclosed).


## **Raw data archive 2023**
2023-08-19  

The source data downloaded from FAOSTAT is archived at a [Zenodo repository]( https://zenodo.org/deposit/8260225).

