# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_xfaostat_L401_Fertilizer
#'
#' process FAOSTAT forestry data (FO) into gcamdata inputs
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs, a vector of output names, or (if
#'   \code{command} is "MAKE") all the generated outputs
#' @details This chunk compiles balanced supply utilization data in primary equivalent in GCAM region and commodities.
#' @importFrom assertthat assert_that
#' @importFrom dplyr summarize bind_rows filter if_else inner_join left_join mutate rename select n group_by_at
#' first case_when vars
#' @importFrom tibble tibble
#' @importFrom tidyr complete drop_na gather nesting spread replace_na fill
#' @author XZ 2023
module_xfaostatL401_Fertilizer <- function(command, ...) {

  MODULE_INPUTS <-
    c(FILE = "aglu/FAO/FAO_an_items_PRODSTAT",
      FILE = "aglu/FAO/FAO_ag_items_PRODSTAT"
      )

  MODULE_OUTPUTS <-
    c("GCAMDATA_FAOSTAT_NFertilizerProdDemand_175Regs_1Item_1973to2020")

  if(command == driver.DECLARE_INPUTS) {
    return(MODULE_INPUTS)
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(MODULE_OUTPUTS)
  } else if(command == driver.MAKE) {

    year <- value <- Year <- Value <- FAO_country <- iso <- NULL    # silence package check.

    all_data <- list(...)[[1]]

    # Load required inputs ----

    get_data_list(all_data, MODULE_INPUTS, strip_attributes = TRUE)

    FAOSTAT_load_raw_data(DATASETCODE = "RFN", DATA_FOLDER = DIR_RAW_DATA_FAOSTAT)

    ## Proprocess and quick clean ----
    FF_summary("RFN")
    RFN %>% distinct(element, element_code, unit)
    RFN %>% distinct(area, area_code)
    RFN %>% distinct(item, item_code)


    ## Preprocess and quick clean ----
    # Only keep Arable land
    RFN %>% filter(year %in% FAOSTAT_Hist_Year,
                   element_code %in% c(5510, 5157),  # Prod and Ag use
                   area_code < 350,                  # Rm aggregated area
                   item_code %in% c(3102)) %>%       # Nutrient nitrogen N (total)
      select(area_code, area, item_code, item, element_code, element, year, value, unit) %>%
      # Complete all dimensions
      complete(nesting(area_code, area), nesting(item_code, item), nesting(element_code, element, unit), year) %>%
      rm_accent("item", "area") -> RFN1

    rm(RFN) # clean

    ## RFN1_Production ----
    RFN1 %>%
      filter(element_code %in% c(5510)) %>%  # Prod
      filter(item_code == 3102) %>%
      group_by(area_code, area, item_code, item) %>%
      # linearly interpolate only forward!
      # then NA = 0
      mutate(value = gcamdata::approx_fun(year, value)) %>%
      # Also Not fill area backward
      fill(value, .direction = "downup") %>%
      replace_na(list(value = 0)) %>%
      # Remove area x year that should not exist
      ungroup() %>%
      FAO_AREA_RM_NONEXIST(RM_AREA_CODE = NULL)  ->
      RFN1_Production

    ## RFN1_Demand ----
    # Ag use

    RFN1 %>%
      filter(element_code %in% c(5157)) %>%  # Prod
      filter(item_code == 3102) %>%
      group_by(area_code, area, item_code, item) %>%
      # linearly interpolate only forward!
      # then NA = 0
      mutate(value = gcamdata::approx_fun(year, value)) %>%
      # Also Not fill area backward
      fill(value, .direction = "downup") %>%
      replace_na(list(value = 0)) %>%
      # Remove area x year that should not exist
      ungroup() %>%
      FAO_AREA_RM_NONEXIST(RM_AREA_CODE = NULL)  ->
      RFN1_Demand

    rm(RFN1) # clean


    ## Produce output and export CSV ----

    RFN1_Production %>%
      bind_rows(RFN1_Demand) %>%
      spread(year, value) ->
      GCAMDATA_FAOSTAT_NFertilizerProdDemand_175Regs_1Item_1973to2020

    GCAMDATA_FAOSTAT_NFertilizerProdDemand_175Regs_1Item_1973to2020 %>%
      add_title("FAO fertilizer production by country_year") %>%
      add_units("tonnes N") %>%
      add_comments("Data is preprocessed and generated by gamdata-FAOSTAT") ->
      GCAMDATA_FAOSTAT_NFertilizerProdDemand_175Regs_1Item_1973to2020

    if (OUTPUT_Export_CSV == T) {

      output_csv_data("GCAMDATA_FAOSTAT_NFertilizerProdDemand_175Regs_1Item_1973to2020",
                      col_type_nonyear = "icicicc",
                      title = "FAO fertilizer production by country_year",
                      unit = "tonnes N",
                      description = "Data is preprocessed and generated by gamdata-FAOSTAT",
                      code = "RFN",
                      out_dir = DIR_OUTPUT_CSV)
    }

    return_data(MODULE_OUTPUTS)

  } else {
    stop("Unknown command")
  }
}
