# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_xfaostat_L301_LandCover
#'
#' process FAOSTAT FAO land data (RL) into gcamdata inputs
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs, a vector of output names, or (if
#'   \code{command} is "MAKE") all the generated outputs
#' @details This chunk compiles balanced supply utilization data in primary equivalent in GCAM region and commodities.
#' @importFrom assertthat assert_that
#' @importFrom dplyr summarize bind_rows filter if_else inner_join left_join mutate rename select n group_by_at
#' first case_when vars
#' @importFrom tibble tibble
#' @importFrom tidyr complete drop_na gather nesting spread replace_na fill
#' @author XZ 2023
module_xfaostat_L301_LandCover <- function(command, ...) {

  MODULE_INPUTS <-
    c("RL")

  MODULE_OUTPUTS <-
    c("RL_LandCover")

  if(command == driver.DECLARE_INPUTS) {
    return(MODULE_INPUTS)
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(MODULE_OUTPUTS)
  } else if(command == driver.MAKE) {

    year <- value <- Year <- Value <- FAO_country <- iso <- NULL    # silence package check.
    item_code <- item <- area_code <- area <- unit <- element_code <- element <- RL <- NULL

    all_data <- list(...)[[1]]

    # Load required inputs ----

    get_data_list(all_data, MODULE_INPUTS, strip_attributes = TRUE)


    ## Proprocess and quick clean ----
    #FF_summary("RL")
    RL %>% distinct(element, element_code, unit)
    RL %>% distinct(area, area_code)
    RL %>% distinct(item, item_code)

    ## Proprocess and quick clean ----
    # Only keep Arable land
    RL %>%
      select(area_code,
             area,
             item_code,
             item,
             element_code,
             element,
             year,
             value,
             unit) %>%
      # Complete all dimensions
      complete(
        nesting(area_code, area),
        nesting(item_code, item),
        nesting(element_code, element, unit),
        year
      ) %>%
      rm_accent("item", "area") -> RL1
    #rm(RL)

    ## RL1_ArableLand ----
    RL1 %>%
      filter(element_code %in% c(5110)) %>%  # Area
      filter(item_code == 6621) %>%  # Arable land
      group_by(area_code, area, item_code, item) %>%
      # linearly interpolate only forward!
      # then NA = 0
      mutate(value = approx_fun(year, value)) %>%
      # Also fill area backward
      fill(value, .direction = "downup") %>%
      replace_na(list(value = 0)) %>%
      # Remove area x year that should not exist
      FAOSTAT_AREA_RM_NONEXIST(RM_AREA_CODE = NULL) %>%
      ungroup() ->
      RL1_ArableLand


    ## RL2_TemporaryCrop ----
    RL1 %>%
      filter(element_code %in% c(5110)) %>%  # Area
      filter(item_code == 6630) %>%  # Temporary crops
      group_by(area_code, area, item_code, item) %>%
      # linearly interpolate only forward!
      # then NA = 0
      mutate(value = approx_fun(year, value)) %>%
      # NOT fill area backward
      # fill(value, .direction = "downup") %>%
      # replace_na(list(value = 0)) %>%
      # Remove area x year that should not exist
      FAOSTAT_AREA_RM_NONEXIST(RM_AREA_CODE = NULL) %>%
      ungroup() ->
      RL2_TemporaryCrop


    ## RL3_FallowLand ----
    RL1 %>%
      filter(element_code %in% c(5110)) %>%  # Area
      filter(item_code == 6640) %>%  # Fallow Land
      group_by(area_code, area, item_code, item) %>%
      # linearly interpolate only forward!
      # then NA = 0
      mutate(value = approx_fun(year, value)) %>%
      # NOT fill area backward
      # fill(value, .direction = "downup") %>%
      # replace_na(list(value = 0)) %>%
      # Remove area x year that should not exist
      FAOSTAT_AREA_RM_NONEXIST(RM_AREA_CODE = NULL) %>%
      ungroup() ->
      RL3_FallowLand

    rm(RL1) # Clean


    ## Produce output and export CSV ----

    RL1_ArableLand %>%
      bind_rows(RL2_TemporaryCrop) %>%
      bind_rows(RL3_FallowLand) ->
      RL_LandCover

    RL_LandCover %>%
      add_title("FAO cropland, Temporary Crop (harvested cropland), and fallow area by country_year") %>%
      add_units("1000 Ha") %>%
      add_comments("Data is cleaned and generated by gcamdata-FAOSTAT") %>%
      add_precursors("RL") ->
      RL_LandCover


    return_data(MODULE_OUTPUTS)

  } else {
    stop("Unknown command")
  }
}
