# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_xfaostat_L200_ExportCSV
#'
#' Generate supply utilization balance in primary equivalent
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs, a vector of output names, or (if
#'   \code{command} is "MAKE") all the generated outputs
#' @details This chunk compiles balanced supply utilization data in primary equivalent in GCAM region and commodities.
#' @importFrom assertthat assert_that
#' @importFrom dplyr summarize bind_rows filter if_else inner_join left_join mutate rename select n group_by_at
#' first case_when vars
#' @importFrom tibble tibble
#' @importFrom tidyr complete drop_na gather nesting spread replace_na
#' @author XZ 2022
module_xfaostat_L200_ExportCSV <- function(command, ...) {

  MODULE_INPUTS <-
    c("Bal_new_all",
      "FBSH_CB",
      "QCL_PROD",
      "QCL_AN_LIVEANIMAL",
      "QCL_AN_PRIMARY_MILK",
      "QCL_CROP_PRIMARY",
      "QCL_FODDERCROP",
      "QCL_PRIMARY_PROD_PV",
      "TM_bilateral",
      "PD",
      "SUA_food_macronutrient_rate")

  MODULE_OUTPUTS <-
    c("xfaostat_L199_DUMMY")

  if(command == driver.DECLARE_INPUTS) {
    return(MODULE_INPUTS)
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(MODULE_OUTPUTS)
  } else if(command == driver.MAKE) {

    year <- value <- Year <- Value <- FAO_country <- iso <- NULL    # silence package check.

    all_data <- list(...)[[1]]


    # adding dummy output ----
    xfaostat_L199_DUMMY <- data.frame()

    if (OUTPUT_Export_CSV == T) {
      # Load required inputs ----

      get_data_list(all_data, MODULE_INPUTS, strip_attributes = TRUE)


      # Bilateral trade ----
      ## *GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020 ----

      TM_bilateral %>%
        # only export quality data years
        filter(year >= min(FAOSTAT_Hist_Year_FBS)) %>%
        FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(SUDAN2012_MERGE = T) %>%
        # merge Sudan and South Sudan
        FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(
          .FAO_AREA_CODE_COL = "source_code",
          .AREA_COL = "source",
          SUDAN2012_MERGE = T
        ) %>%
        filter(value != 0.0) %>%
        transmute(area_code, item_code, source_code, year, value) ->
        GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020


      output_csv_data(
        "GCAMDATA_FAOSTAT_BiTrade_194Regs_400Items_2010to2020",
        col_type_nonyear = "iiiin",
        title = "BiTrade for all available FAO items in 2010 to 2019",
        unit = "1000 tonnes",
        code = "TM",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. Bilateral trade data.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )



      # SUA and FBS ----
      ## *GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019 ----

      Bal_new_all %>% filter(value != 0.0) %>%
        transmute(area_code, item_code, element, year, value) ->
        GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019

      output_csv_data(
        "GCAMDATA_FAOSTAT_SUA_195Regs_530Items_2010to2019",
        col_type_nonyear = "iifin",
        title = "Supply_utilization_accounting for all FAO items in 2010 to 2019",
        unit = "1000 tonnes",
        code = "SCL",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. Data is balanced in trade, supply_utilization, and storage",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )

      ## *GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009 ----

      FBSH_CB %>%
        select(-element_code) %>%
        # merge Sudan and South Sudan
        FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(SUDAN2012_MERGE = T) ->
        FBSH_CB

      FBSH_CB %>%
        mutate(unit = "1000 tonnes", value = value / 1000) %>%
        filter(year <= 2009)  %>%
        filter(!is.na(year)) %>%
        spread(year, value) ->
        GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009

      output_csv_data(
        "GCAMDATA_FAOSTAT_FBSH_CB_173Regs_118Items_1973to2009",
        col_type_nonyear = "iiccc",
        title = "Old FAO food balance sheet in primary equilvalent in 1973 to 2009",
        unit = "1000 tonnes",
        code = "FBSH",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. FBSH and CB include old food and nonfood balances.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )


      # Production and Area harvested ----
      ## *GCAMDATA_FAOSTAT_ProdArea_195Regs_271Prod160AreaItems_1973to2020 ----
      ## *GCAMDATA_FAOSTAT_ProdArea_96Regs_16FodderItems_1973to2020 ----


      for (.DF in c("QCL_CROP_PRIMARY", "QCL_FODDERCROP", "QCL_PROD")) {
        get(.DF) %>%
          # merge Sudan and South Sudan
          FAO_AREA_DISAGGREGATE_HIST_DISSOLUTION_ALL(SUDAN2012_MERGE = T) %>%
          assign(x = .DF, envir = parent.env(environment()))
      }

      QCL_CROP_PRIMARY %>%
        filter(element == "Area harvested") %>%
        mutate(item_set = "QCL_COMM_CROP_PRIMARY") %>%
        bind_rows(QCL_PROD %>%
                    filter(!is.na(year))) %>%
        select(-element_code) %>%
        mutate(value = value / 1000) %>%
        mutate(unit = if_else(unit == "tonnes", "1000 tonnes", "1000 ha")) %>%
        spread(year, value) ->
        GCAMDATA_FAOSTAT_ProdArea_195Regs_271Prod160AreaItems_1973to2020


      QCL_FODDERCROP %>%
        filter(!is.na(year)) %>%
        select(-element_code) %>%
        mutate(value = value / 1000) %>%
        mutate(unit = if_else(unit == "tonnes", "1000 tonnes", "1000 ha")) %>%
        spread(year, value) ->
        GCAMDATA_FAOSTAT_ProdArea_96Regs_16FodderItems_1973to2020


      output_csv_data(
        "GCAMDATA_FAOSTAT_ProdArea_195Regs_271Prod160AreaItems_1973to2020",
        col_type_nonyear = "iiccccc",
        title = "Production and harvested area for FAO items in 1973 to 2020",
        unit = "1000 tonnes or 1000 ha",
        code = "QCL",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. Data is cleaned mainly based on QCL from FAOSTAT.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )


      output_csv_data(
        "GCAMDATA_FAOSTAT_ProdArea_96Regs_16FodderItems_1973to2020",
        col_type_nonyear = "iicccc",
        title = "Production and harvested area for fodder crops in 1973 to 2020",
        unit = "1000 tonnes or 1000 ha",
        code = "QCL",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. Data is extrapolated based on old FAOSTAT data (to 2012) used in gcamdata.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )


      # Animal stocks ----
      #**GCAMDATA_FAOSTAT_AnimalStock_202Regs_22Items_1973to2020 ----
      # Laying is not needed for now; live animal stocks and milk animals are used for water demand calculation in GCAM
      # 1171 "Animals live nes" and 1083 "Pigeons, other birds" are not available


      QCL_AN_LIVEANIMAL %>% filter(element == "Stocks") %>%
        spread(year, value) -> FAO_an_Stocks

      QCL_AN_PRIMARY_MILK %>% filter(element == "Milk Animals") %>%
        spread(year, value) -> FAO_an_Dairy_Stocks

      FAO_an_Stocks %>% bind_rows(FAO_an_Dairy_Stocks) -> GCAMDATA_FAOSTAT_AnimalStock_202Regs_22Items_1973to2020

      output_csv_data(
        "GCAMDATA_FAOSTAT_AnimalStock_202Regs_22Items_1973to2020",
        col_type_nonyear = "icicicc",
        title = "FAO all meat animal stock and milk animal stock by area_item_year",
        unit = "Head, 1000 Head or No",
        code = "QCL",
        description = "Data is preprocessed and generated by gcamdata-FAOSTAT",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )


      # Producer prices in quantity and value ----
      # **GCAMDATA_FAOSTAT_ProducerPrice_170Regs_185PrimaryItems_2010to2020 ----


      FAO_ag_an_ProducerPrice <- QCL_PRIMARY_PROD_PV %>%
        filter(year >= MIN_HIST_PP_YEAR) %>% spread(year, value)

      FAO_ag_an_ProducerPrice %>% distinct(area)
      FAO_ag_an_ProducerPrice ->
        GCAMDATA_FAOSTAT_ProducerPrice_170Regs_185PrimaryItems_2010to2020

      output_csv_data(
        "GCAMDATA_FAOSTAT_ProducerPrice_170Regs_185PrimaryItems_2010to2020",
        col_type_nonyear = "iciccc",
        title = "FAO primary Ag and An production quantity and value by area_item_year for prices derivation",
        unit = "Quantity in tonne; Value in US$",
        code = "PP",
        description = "Data is preprocessed and generated by gcamdata-FAOSTAT. Processed QCL was also used. Missing values filled in.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )
      rm(QCL_PRIMARY_PROD_PV, FAO_ag_an_ProducerPrice)


      ###** GDP deflators ----

      FAO_GDP_Deflators <-
        PD %>% FAO_AREA_RM_NONEXIST(RM_AREA_CODE = NULL) %>%
        spread(year, value)

      output_csv_data(
        "FAO_GDP_Deflators",
        col_type_nonyear = "cicici",
        title = "FAO GDP deflators by country (2015 = 100)",
        unit = "Unitless",
        code = "PD",
        description = "FAOSTAT (domain:PD) & Taiwan Statistics (access:4-12-2021)",
        out_dir = DIR_OUTPUT_CSV
      )

      # Macronutrient ----

      ## *GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean----


      SUA_food_macronutrient_rate ->
        GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean


      # Fix Sudan with code 206 and 276 after 2012
      if (206 %in% GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean$area_code == F) {
        GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean %>%
          filter(area_code  == 276) %>% mutate(area_code  = 206) %>%
          bind_rows(GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean) ->
          GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean
      }


      output_csv_data(
        "GCAMDATA_FAOSTAT_MacroNutrientRate_179Regs_426Items_2010to2019Mean",
        col_type_nonyear = "iicnnn",
        title = "Macronutrient conversion factor for food items, mean values of 2010 to 2019",
        unit = "calories per g or (fat or protein) percentage",
        code = "SCL",
        description = "Data is compiled and generated by gcamdata-FAOSTAT. Macronutrient conversion factor for all available FAO food items.",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = T
      )

    }



    return_data(MODULE_OUTPUTS)


  } else {
    stop("Unknown command")
  }
}
