# Copyright 2019 Battelle Memorial Institute; see the LICENSE file.

#' module_yfaostat_SUA_FBS_CSVExport
#'
#' Generate supply utilization balance in primary equivalent
#'
#' @param command API command to execute
#' @param ... other optional parameters, depending on command
#' @return Depends on \code{command}: either a vector of required inputs, a vector of output names, or (if
#'   \code{command} is "MAKE") all the generated outputs
#' @details This chunk compiles balanced supply utilization data in primary equivalent in GCAM region and commodities.
#' @importFrom assertthat assert_that
#' @importFrom dplyr summarize bind_rows filter if_else inner_join left_join mutate rename select n group_by_at
#' first case_when vars
#' @importFrom tibble tibble
#' @importFrom tidyr complete drop_na gather nesting spread replace_na
#' @author XZ Sep2024
module_yfaostat_SUA_FBS_CSVExport <- function(command, ...) {

  MODULE_INPUTS <-
    c(FILE = file.path(DIR_RAW_DATA_FAOSTAT, "Mapping_SUA_PrimaryEquivalent"),
      FILE = file.path(DIR_RAW_DATA_FAOSTAT, "SUA_item_code_map"),
      FILE = file.path(DIR_RAW_DATA_FAOSTAT, "Mapping_FAO_iso_reg"),
      "GCAM_APE_after2010",
      "Bal_new_all",
      "FBS_wide",
      "FAO_Food_Macronutrient_All")

    MODULE_OUTPUTS <-
      c(CSV = "GCAMFAOSTAT_DataArchive_SUA")

  if(command == driver.DECLARE_INPUTS) {
    return(MODULE_INPUTS)
  } else if(command == driver.DECLARE_OUTPUTS) {
    return(MODULE_OUTPUTS)
  } else if(command == driver.MAKE) {

    year <- value <- Year <- Value <- FAO_country <- iso <- NULL    # silence package check.

    all_data <- list(...)[[1]]


    Curr_Envir <- environment()



    if (OUTPUT_Export_CSV == "DataArchive_SUA_FBS") {

      # Load required inputs ----
      get_data_list(all_data, MODULE_INPUTS, strip_attributes = TRUE)


      # SUA and FBS ----
      ## *SUA ----

      Bal_new_all %>% filter(value != 0.0) %>%
        transmute(area_code, item_code, element, year, value) %>%
        add_title("GCAMFAOSTAT_DataArchive_SUA") %>%
        add_units("1000 tonnes") %>%
        add_comments("gcamfaostat Export CSV") %>%
        add_precursors("Bal_new_all") ->
        GCAMFAOSTAT_DataArchive_SUA


      output_csv_data(
        gcam_dataset = GCAMFAOSTAT_DataArchive_SUA,
        out_filename = "GCAMFAOSTAT_DataArchive_SUA",
        col_type_nonyear = "iifin",
        title = "Supply_utilization_accounting for all FAO items in FAOSTAT_Hist_Year_FBS",
        unit = "1000 tonnes",
        code = "SCL",
        description = "Data is compiled and generated by gcamfaostat. Data is balanced in trade, supply_utilization, and storage",
        out_dir = DIR_OUTPUT_CSV,
        GZIP = F)

      rm(Bal_new_all)


      }
    else {

        lapply(MODULE_OUTPUTS[MODULE_OUTPUTS %>% names() == "CSV"],
               function(output){
                 assign(output, empty_data() %>%
                          add_title(output), envir =  Curr_Envir)
               })
        }


    return_data(MODULE_OUTPUTS)

  } else {
    stop("Unknown command")
  }
}
