on: [push, pull_request]

name: osx

jobs:
  build:

    runs-on: macOS-latest

    strategy:
      matrix:
        r: ['4.1', 'release']

    steps:
      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@main
        with:
          r-version: ${{ matrix.r }}

      - uses: r-lib/actions/setup-pandoc@main

      - uses: r-lib/actions/setup-tinytex@main

      - name: Install dependencies
        env:
          R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
        run: Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'covr'))" -e "remotes::install_deps(dependencies = TRUE)"

      - name: Check
        run: Rscript -e "rcmdcheck::rcmdcheck(error_on = 'error')"

      - name: Test coverage
        if: matrix.r == '3.6'
        run: |
          Rscript -e 'remotes::install_github("r-lib/covr@gh-actions")'
          Rscript -e 'covr::codecov(token = "${{secrets.CODECOV_TOKEN}}")'
