name: R-CMD-check

on:
  push:
    branches:
      - main

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: 4.0

      - name: Install dependencies
        run: R -e 'install.packages(c("devtools", "roxygen2"))'

      - name: R CMD check
        run: R CMD check .

      - name: Install package
        run: R -e 'devtools::install()'

      - name: Run tests
        run: R -e 'devtools::test()'