# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['4.1.0']

    steps:
      - uses: actions/checkout@v2
        
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2-branch
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v2-branch
      - uses: r-lib/actions/setup-tinytex@v2-branch

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies including Pandoc
        run: |
          sudo apt-get update -q
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libudunits2-dev libgdal-dev libgeos-dev libproj-dev libmagick++-dev libavfilter-dev
          sudo apt-get install -y pandoc
        shell: bash
        
      - name: Install dependencies
        run: |
          R -e "install.packages(c('remotes', 'rcmdcheck'), repos = 'https://cloud.r-project.org')"
          R -e "install.packages('kableExtra', repos = 'https://cloud.r-project.org')"
          R -e "remotes::install_deps(dependencies = TRUE)"
        shell: bash
        
      - name: Check
        run: |
          R -e "rcmdcheck::rcmdcheck(args = '--no-manual --no-vignettes', error_on = 'error')"
        shell: bash